services:
  postgres:
    image: postgres:17

    container_name: trippoint-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: trippoint
      POSTGRES_USER: trippoint
      POSTGRES_PASSWORD: trippoint

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: