type Query {
    me: User!
    userDevices: [UserDevice!]!
}

type User {
    id: ID!
    email: String!
    firstName: String
    lastName: String
}

type UserDevice {
    id: ID!
    deviceName: String
    platform: String
    appVersion: String
    lastLoginAt: String
    createdAt: String!
}

input RegisterInput {
    email: String!
    password: String!
    firstName: String!
    lastName: String!
}

type AuthPayload {
    user: User!
    token: String!
    refreshToken: String!
}

type Mutation {
    register(input: RegisterInput!): AuthPayload!
    login(email: String!, password: String!): AuthPayload!
}

input RefreshTokenInput {
    refreshToken: String!
}

type RefreshTokenPayload {
    token: String!
    refreshToken: String!
}

extend type Mutation {
    refreshToken(input: RefreshTokenInput!): RefreshTokenPayload!
    logout: Boolean!
    logoutAllDevices: Boolean!
    changePassword(currentPassword: String!, newPassword: String!): Boolean!
}
