package com.trippoint.backend.notification.model

enum class NotificationType {
    TRIP_INVITATION,
    TRIP_UPDATED,

    INVITATION_ACCEPTED,
    INVITATION_DECLINED,

    MEMBER_ADDED,
    MEMBER_REMOVED,

    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_UPDATED,
    BOOKING_CANCELLED,

    EXPENSE_ADDED,
    EXPENSE_UPDATED,
    EXPENSE_SETTLEMENT,

    CHECKLIST_ASSIGNED,
    CHECKLIST_DUE,
    CHECKLIST_OVERDUE,
    CHECKLIST_COMPLETED,

    DOCUMENT_UPLOADED,
    DOCUMENT_UPDATED,
    DOCUMENT_EXPIRING,

    CHAT_MENTION,
    CHAT_REPLY,

    REMINDER_DUE,
    REMINDER_OVERDUE,

    SYSTEM_ALERT,
}